import type { Metadata } from "next";
import {clsx} from 'clsx';
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/src/theme/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Thread",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      
        <body className={clsx(inter.className, 'bg-background h-full')}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div className="flex flex-col h-full">
              <div className="flex-1 max-w-lg m-auto py-12 w-full">
                {children}
              </div>
            </div>
            
            </ThemeProvider>
        </body>
     
    </html>
  );
}
